package StringOperations;

/**
* StringOperations/StringServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperations.idl
* Wednesday, May 7, 2025 12:13:59 PM IST
*/

public final class StringServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public StringOperations.StringService value = null;

  public StringServiceHolder ()
  {
  }

  public StringServiceHolder (StringOperations.StringService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringOperations.StringServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringOperations.StringServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringOperations.StringServiceHelper.type ();
  }

}
