package StringOperations;


/**
* StringOperations/StringService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperations.idl
* Wednesday, May 7, 2025 12:13:59 PM IST
*/

public interface StringService extends StringServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringService
