package StringOperations;


/**
* StringOperations/StringServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperations.idl
* Wednesday, May 7, 2025 12:13:59 PM IST
*/

abstract public class StringServiceHelper
{
  private static String  _id = "IDL:StringOperations/StringService:1.0";

  public static void insert (org.omg.CORBA.Any a, StringOperations.StringService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StringOperations.StringService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StringOperations.StringServiceHelper.id (), "StringService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StringOperations.StringService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StringServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StringOperations.StringService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StringOperations.StringService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringOperations.StringService)
      return (StringOperations.StringService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringOperations._StringServiceStub stub = new StringOperations._StringServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StringOperations.StringService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringOperations.StringService)
      return (StringOperations.StringService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringOperations._StringServiceStub stub = new StringOperations._StringServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
