package StringOperations;


/**
* StringOperations/StringServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperations.idl
* Wednesday, May 7, 2025 12:13:59 PM IST
*/

public interface StringServiceOperations 
{
  String concatenate (String str1, String str2);
  String reverse (String str);
  String toUpperCase (String str);
  String toLowerCase (String str);
  int getLength (String str);
  boolean contains (String str, String substring);
  String substring (String str, int start, int end);
} // interface StringServiceOperations
